version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - ./envs/backend.env
    volumes:
      - backend_data:/var/lib/backend/data

  migrate:
    build:
      context: .
    command: python manage.py migrate
    env_file:
      - ./envs/backend.env
      
  postgres:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./envs/postgres.env
    ports:
      - 5432:5432
    restart: unless-stopped
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/sharkdeck/staticfiles
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  backend_data:

