# Generated by Django 3.2.9 on 2023-02-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cash_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cheque_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_range',
            field=models.PositiveIntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
